=== AlumAlbertoPiedra/EX_UD4_AlbertoPiedra/pedidos.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pedido (sucursal+, articulo+)>
<!ELEMENT sucursal (direccion+ , nombre, fecha, observaciones?)>
<!ATTLIST sucursal codigo CDDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulo(unidadesPedidas, precioUnidad, observacionesArticulo?, plazoRevision)>
<!ATTLIST articulo codigo CDDATA #REQUIRED>
<!ELEMENT unidadesPedidas (#PCDATA)>
<!ELEMENT precioUnidad (#PCDATA)>
<!ELEMENT observacionesArticulo (#PCDATA)>
<!ELEMENT plazoRevision (#PCDATA)>

=== AlumAlbertoPiedra/EX_UD4_AlbertoPiedra/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">
<pedido>
    <sucursal codigo="A00001524">
        <direccion> Calle Genil </direccion>
        <nombre> Andres </nombre>
        <fecha> 17/04/2020 </fecha>
        <observaciones> incompleto </observaciones>
    </sucursal>
    <articulo codigo="ABC-313">
        <unidadesPedidas> 12 </unidadesPedidas>
        <precioUnidad> 10 </precioUnidad>
        <observacionesArticulo> Pack de 12 gominolas </observacionesArticulo>
        <plazoRevision> 20 </plazoRevision>
    </articulo>
</pedido>
